services:
  solver:
    image: tsp:solver
    ports:
    - ${SOLVER_PORT}:${SOLVER_PORT}
    environment:
    - SOLVER_PORT
    - WEBAPP_PORT
    - DEBUG_MODE
    networks:
    - tsp

  webapp:
    image: tsp:webapp
    ports:
    - ${WEBAPP_PORT}:${WEBAPP_PORT}
    environment:
    - SOLVER_PORT
    - WEBAPP_PORT
    - DEBUG_MODE
    - AWS_EKS
    networks:
    - tsp

networks:
  tsp: {}
