services:
  solver:
    image: tsp:solver
    ports:
      - "${SOLVER_PORT}:${SOLVER_PORT}"
    environment:
      SOLVER_PORT: ${SOLVER_PORT}
      WEBAPP_PORT: ${WEBAPP_PORT}
    networks:
      - tsp

  webapp:
    image: tsp:webapp
    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"
    environment:
      SOLVER_PORT: ${SOLVER_PORT}
      WEBAPP_PORT: ${WEBAPP_PORT}
    networks:
      - tsp

networks:
  tsp: {}
