FROM python:3.11-slim-buster

ARG SOLVER_PORT
ENV SOLVER_PORT=$SOLVER_PORT

ARG WEBAPP_PORT
ENV WEBAPP_PORT=$WEBAPP_PORT

COPY requirements.webapp.txt /app/requirements.txt
WORKDIR /app

RUN pip install -r requirements.txt

COPY src/webapp.py /app/src/
COPY src/utils.py /app/src/

COPY src/static/readPos.js /app/src/static/
COPY src/static/imgs/background.png /app/src/static/imgs/
COPY src/templates/main.html /app/src/templates/

EXPOSE $WEBAPP_PORT/tcp
CMD [ "python3", "-m", "src.webapp" ]
