FROM python:3.11-slim-buster

COPY requirements.solver.txt /app/requirements.txt
WORKDIR /app

RUN pip install -r requirements.txt

COPY src/solver.py /app/src/
COPY src/solver_api.py /app/src/

EXPOSE 8118/tcp
CMD [ "python3", "-m", "src.solver_api" ]
